### ISSUE TITLE
windows 启动后报这个 Notice: ffmpeg is not installe 这个有影响吗

### ISSUE THREAD

**Issue by plane55** [jianchang512/zh_recogn#9]
Notice: ffmpeg is not installed. torchaudio is used to load audio
If you want to use ffmpeg backend to load audio, please install it by:
        sudo apt install ffmpeg # ubuntu
        # brew install ffmpeg # ma

**Comment by plane55** [comment]
然后 上传视频报 upload failed
![image](https://github.com/user-attachments/assets/584372d5-048d-420d-b8c3-81b3710a4fa4)

**Comment by jianchang512** [comment]
当然有影响，按提示安装 ffmpeg

**Comment by plane55** [comment]
我是 windows 打包版

**Comment by jianchang512** [comment]
重试，截图终端窗口中输出的信息

**Comment by plane55** [comment]
![image](https://github.com/user-attachments/assets/bddeffc4-4f9a-4986-9a7b-ddc758ec99b9)

**Comment by plane55** [comment]
可以了
